# SPDX-FileCopyrightText: 2024, Yaskawa America, Inc.
# SPDX-FileCopyrightText: 2024, Delft University of Technology
#
# SPDX-License-Identifier: Apache-2.0

uint32 RC_OK=1
string STR_OK="Success"

uint32 RC_ERR_REFRESHING_JOB_LIST=10
string STR_ERR_REFRESHING_JOB_LIST="Error refreshing job list"

uint32 RC_ERR_RETRIEVING_FILE_COUNT=11
string STR_ERR_RETRIEVING_FILE_COUNT="Error retrieving file count"

uint32 RC_ERR_TOO_MANY_JOBS=12
string STR_ERR_TOO_MANY_JOBS="Too many jobs"

uint32 RC_ERR_RETRIEVING_JOB_NAME_FROM_LIST=13
string STR_ERR_RETRIEVING_JOB_NAME_FROM_LIST="Failed retrieving job name from list"

uint32 RC_ERR_APPENDING_JOB_NAME_TO_SVC_RESPONSE=14
string STR_ERR_APPENDING_JOB_NAME_TO_SVC_RESPONSE="Error adding job name to service response"
